In [7]:
from pathlib import Path
import pandas as pd

PROJECT_DIR = Path("/Users/zurabi/Desktop/ML_FINAL_PROJECT")

In [8]:
import zipfile

zip_path = PROJECT_DIR / "walmart-recruiting-store-sales-forecasting.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(PROJECT_DIR)

In [9]:
train = pd.read_csv(PROJECT_DIR / "train.csv.zip")
test = pd.read_csv(PROJECT_DIR / "test.csv.zip")
features = pd.read_csv(PROJECT_DIR / "features.csv.zip")
stores = pd.read_csv(PROJECT_DIR / "stores.csv")
sample_submission = pd.read_csv(PROJECT_DIR / "sampleSubmission.csv.zip")

In [15]:
print(f"train shape: {train.shape}")
print(train.dtypes)
train.head()

train shape: (421570, 5)
Store             int64
Dept              int64
Date             object
Weekly_Sales    float64
IsHoliday          bool
dtype: object

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [11]:
print(f"test shape: {test.shape}")
test.head()

test shape: (115064, 4)

   Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False
1      1     1  2012-11-09      False
2      1     1  2012-11-16      False
3      1     1  2012-11-23       True
4      1     1  2012-11-30      False

In [12]:
print(f"features shape: {features.shape}")
features.head()

features shape: (8190, 12)

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [ ]:
print(f"stores shape: {stores.shape}")
stores.head()

stores shape: (45, 3)

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [16]:
train["Date"] = pd.to_datetime(train["Date"])
test["Date"] = pd.to_datetime(test["Date"])
features["Date"] = pd.to_datetime(features["Date"])

##### Here we compare train and test dates. test dates come after train dates

In [18]:
print("Train dates:", train["Date"].min(), "to", train["Date"].max())
print("Test dates:", test["Date"].min(), "to", test["Date"].max())
print("Features dates:", features["Date"].min(), "to", features["Date"].max())

Train dates: 2010-02-05 00:00:00 to 2012-10-26 00:00:00
Test dates: 2012-11-02 00:00:00 to 2013-07-26 00:00:00
Features dates: 2010-02-05 00:00:00 to 2013-07-26 00:00:00